version: '2'
services:
 elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
   environment:
     - xpack.security.enabled=false
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
   ports:
     - 9200:9200
     - 9300:9300

 kibana:
   image: docker.elastic.co/kibana/kibana:6.5.4
   environment:
     ELASTICSEARCH_URL: http://elasticsearch:9200
   ports:
     - 5601:5601
